<?php

namespace App\Actions\Wards\KidneyTransplantAdmission;

use App\Extensions\Auth\AvatarUser;
use App\Models\User;
use Illuminate\Support\Facades\Validator;
use Illuminate\Validation\Rule;

class CaseRecordUpdateAction extends KidneyTransplantAdmissionAction
{
    public function __invoke(array $data, string $hashedKey, User|AvatarUser $user): array
    {
        if ($link = $this->shouldLinkAvatar()) {
            return $link;
        }

        $caseRecord = $this->getCaseRecord($hashedKey);

        if ($user->cannot('update', $caseRecord)) {
            abort(403);
        }

        $validated = Validator::validate($data, [
            'nephrologist' => ['nullable', 'string', 'max:255'],
            'surgeon' => ['nullable', 'string', 'max:255'],
            'date_off_drain' => ['nullable', 'string', 'max:255'],
            'date_off_foley' => ['nullable', 'string', 'max:255'],
            'insurance' => ['nullable', 'string', 'max:255'],
            'cost' => ['nullable', 'string', 'max:255'],
            'patient_transferred' => ['boolean'],
            'patient_transferred_to' => ['nullable', 'string', 'max:255'],
            'cause_of_esrd' => ['nullable', 'string', 'max:255'],
            'donor_type' => ['nullable', Rule::in($this->CONFIGS['donor_types'])],
            'recipient_is' => ['nullable',
                Rule::in($caseRecord->patient->gender === 'male'
                    ? $this->CONFIGS['male_recipient_is_options']
                    : $this->CONFIGS['female_recipient_is_options'])
                ],
            'donor_is' => ['nullable', Rule::in($this->CONFIGS['donor_is_options'][$data['recipient_is']] ?? [])],
            'blood_group_abo' => ['nullable', Rule::in($this->CONFIGS['abo_options'])],
            'blood_group_rh' => ['nullable', Rule::in($this->CONFIGS['rh_options'])],
            'hla_mismatch_a' => ['nullable', Rule::in($this->CONFIGS['hla_mismatch_options'])],
            'hla_mismatch_b' => ['nullable', Rule::in($this->CONFIGS['hla_mismatch_options'])],
            'hla_mismatch_dr' => ['nullable', Rule::in($this->CONFIGS['hla_mismatch_options'])],
            'hla_mismatch_dq' => ['nullable', Rule::in($this->CONFIGS['hla_mismatch_options'])],
            'pra_class_i_percent' => ['nullable', 'numeric', 'min:0', 'max:100'],
            'pra_class_ii_percent' => ['nullable', 'numeric', 'min:0', 'max:100'],
            'crossmatch_cdc' => ['nullable', Rule::in($this->CONFIGS['crossmatch_options'])],
            'crossmatch_cdc_positive_specification' => ['nullable', 'string', 'max:255'],
            'crossmatch_cdc_ahg' => ['nullable', Rule::in($this->CONFIGS['crossmatch_options'])],
            'crossmatch_cdc_ahg_positive_specification' => ['nullable', 'string', 'max:255'],
            'crossmatch_flow_cxm' => ['nullable', Rule::in($this->CONFIGS['crossmatch_options'])],
            'crossmatch_flow_cxm_positive_specification' => ['nullable', 'string', 'max:255'],
            'clinical_data_attachments' => ['array'],
            'clinical_data_attachments.*' => ['nullable', 'string', 'max:255'],
            'comorbidities' => ['array'],
            'comorbidities.none' => ['boolean'],
            'comorbidities.acute_mi' => ['boolean'],
            'comorbidities.date_acute_mi' => ['nullable', 'date'],
            'comorbidities.unstable_angina' => ['boolean'],
            'comorbidities.date_unstable_angina' => ['nullable', 'date'],
            'comorbidities.CAG' => ['boolean'],
            'comorbidities.date_CAG' => ['nullable', 'date'],
            'comorbidities.PTCA' => ['boolean'],
            'comorbidities.date_PTCA' => ['nullable', 'date'],
            'comorbidities.CABG' => ['boolean'],
            'comorbidities.date_CABG' => ['nullable', 'date'],
            'comorbidities.CAD' => ['boolean'],
            'comorbidities.date_CAD' => ['nullable', 'date'],
            'comorbidities.CVA' => ['boolean'],
            'comorbidities.date_CVA' => ['nullable', 'date'],
            'comorbidities.stroke' => ['boolean'],
            'comorbidities.date_stroke' => ['nullable', 'date'],
            'comorbidities.PVD' => ['boolean'],
            'comorbidities.date_PVD' => ['nullable', 'date'],
            'comorbidities.amputation' => ['boolean'],
            'comorbidities.date_amputation' => ['nullable', 'date'],
            'comorbidities.CHF' => ['boolean'],
            'comorbidities.date_CHF' => ['nullable', 'date'],
            'comorbidities.heart_failure' => ['boolean'],
            'comorbidities.date_heart_failure' => ['nullable', 'date'],
            'comorbidities.HT' => ['boolean'],
            'comorbidities.date_HT' => ['nullable', 'date'],
            'comorbidities.on_HT_medication' => ['boolean'],
            'comorbidities.date_start_HT_medication' => ['nullable', 'date'],
            'comorbidities.HT_medication' => ['nullable', 'string', 'max:255'],
            'comorbidities.DM' => ['boolean'],
            'comorbidities.date_DM' => ['nullable', 'date'],
            'comorbidities.on_DM_medication' => ['boolean'],
            'comorbidities.date_start_DM_medication' => ['nullable', 'date'],
            'comorbidities.DM_medication' => ['nullable', 'string', 'max:255'],
            'comorbidities.COPD' => ['boolean'],
            'comorbidities.date_COPD' => ['nullable', 'date'],
            'comorbidities.asthma' => ['boolean'],
            'comorbidities.date_asthma' => ['nullable', 'date'],
            'comorbidities.TB' => ['boolean'],
            'comorbidities.date_TB' => ['nullable', 'date'],
            'comorbidities.cancer' => ['boolean'],
            'comorbidities.date_cancer' => ['nullable', 'date'],
            'comorbidities.cancer_type' => ['nullable', 'string', 'max:255'],
            'comorbidities.cirrhosis' => ['boolean'],
            'comorbidities.date_cirrhosis' => ['nullable', 'date'],
            'comorbidities.DLP' => ['boolean'],
            'comorbidities.date_DLP' => ['nullable', 'date'],
            'comorbidities.PRCA' => ['boolean'],
            'comorbidities.date_PRCA' => ['nullable', 'date'],
            'comorbidities.uric_greater_than_six' => ['boolean'],
            'comorbidities.date_uric_greater_than_six' => ['nullable', 'date'],
            'comorbidities.on_allopurinol' => ['boolean'],
            'comorbidities.date_start_allopurinol' => ['nullable', 'date'],
            'comorbidities.gout' => ['boolean'],
            'comorbidities.date_gout' => ['nullable', 'date'],
            'comorbidities.hyperparathyroidism' => ['boolean'],
            'comorbidities.date_hyperparathyroidism' => ['nullable', 'date'],
            'comorbidities.PTH_grater_than_one_hundred' => ['boolean'],
            'comorbidities.date_PTH_grater_than_one_hundred' => ['nullable', 'date'],
            'comorbidities.smoking' => ['nullable', Rule::in($this->CONFIGS['smoking_options'])],
            'comorbidities.date_start_smoking' => ['nullable', 'date'],
            'comorbidities.comorbidities_other' => ['nullable', 'string', 'max:255'],
            'datetime_harvest_start' => ['nullable', 'date'],
            'datetime_harvest_finish' => ['nullable', 'date'],
            'datetime_operation_start' => ['nullable', 'date'],
            'datetime_operation_finish' => ['nullable', 'date'],
            'cold_ischemic_time_hours' => ['nullable', 'integer'],
            'cold_ischemic_time_minutes' => ['nullable', 'integer'],
            'warm_ischemic_time_minutes' => ['nullable', 'integer'],
            'anastomosis_time_minutes' => ['nullable', 'integer'],
            'datetime_clamp_at_donor' => ['nullable', 'date'],
            'datetime_perfusion' => ['nullable', 'date'],
            'datetime_remove_from_ice' => ['nullable', 'date'],
            'datetime_unclamp_all' => ['nullable', 'date'],
            'operative_data_attachments' => ['array'],
            'operative_data_attachments.*' => ['nullable', 'string', 'max:255'],
            'graft_function' => ['nullable', Rule::in($this->CONFIGS['graft_function_options'])],
            'delayed_graft_function_dialysis_mode' => ['nullable', Rule::in($this->CONFIGS['dialysis_mode_options'])],
            'date_delayed_graft_function_dialysis_start' => ['nullable', 'date'],
            'delayed_graft_function_dialysis_indication_hyper_k' => ['boolean'],
            'delayed_graft_function_dialysis_indication_volume_overload' => ['boolean'],
            'delayed_graft_function_dialysis_indication_uremia' => ['boolean'],
            'delayed_graft_function_dialysis_indication_other' => ['nullable', 'string', 'max:255'],
            'graft_function_graft_nephrectomy' => ['boolean'],
            'graft_biopsies' => ['array'],
            'graft_biopsies.*.ATN' => ['boolean'],
            'graft_biopsies.*.ATI' => ['boolean'],
            'graft_biopsies.*.rejection' => ['boolean'],
            'graft_biopsies.*.TMA' => ['boolean'],
            'graft_biopsies.*.other_result' => ['nullable', 'string', 'max:255'],
            'graft_biopsies.*.date_biopsy' => ['nullable', 'date'],
            'graft_biopsies.*.attachment' => ['nullable', 'string', 'max:255'],
            'complications' => ['array'],
            'complications.none' => ['boolean'],
            'complications.UTI' => ['boolean'],
            'complications.septicemia' => ['boolean'],
            'complications.pneumonia' => ['boolean'],
            'complications.CMV' => ['boolean'],
            'complications.herpez' => ['boolean'],
            'complications.BK' => ['boolean'],
            'complications.wound_infection' => ['boolean'],
            'complications.infection_other' => ['nullable', 'string', 'max:255'],
            'complications.hematoma' => ['boolean'],
            'complications.blood_transfusion' => ['boolean'],
            'complications.blood_transfusion_unit' => ['nullable', 'integer'],
            'complications.stenosis_a' => ['boolean'],
            'complications.stenosis_v' => ['boolean'],
            'complications.thrombosis_a' => ['boolean'],
            'complications.thrombosis_v' => ['boolean'],
            'complications.complication_other' => ['nullable', 'string', 'max:255'],
            'complications.ureter_stricture' => ['boolean'],
            'complications.leakage' => ['boolean'],
            'complications.urinoma' => ['boolean'],
            'complications.lymphocele' => ['boolean'],
            'complications.ultrasound' => ['boolean'],
            'complications.doppler' => ['boolean'],
            'complications.ct_abdomen' => ['boolean'],
            'complications.CTA' => ['boolean'],
            'complications.CTV' => ['boolean'],
            'complications.renogram' => ['boolean'],
            'complications.attachments' => ['array'],
            'complications.attachments.*' => ['nullable', 'string', 'max:255'],
            'remarks' => ['nullable', 'string', 'max:1024'],
        ]);

        return ['ok' => $caseRecord->update(['form' => $validated])];
    }
}
